FROM confluentinc/cp-kafka-connect:7.8.2
# Download and install Debezium MongoDB connector
RUN mkdir -p /usr/share/confluent-hub-components && \
  curl -L -o /tmp/debezium-connector-mongodb-3.0.8.Final-plugin.tar.gz https://repo1.maven.org/maven2/io/debezium/debezium-connector-mongodb/3.0.8.Final/debezium-connector-mongodb-3.0.8.Final-plugin.tar.gz && \
  tar -xzf /tmp/debezium-connector-mongodb-3.0.8.Final-plugin.tar.gz -C /usr/share/confluent-hub-components && \
  rm /tmp/debezium-connector-mongodb-3.0.8.Final-plugin.tar.gz