services:
  #######################
  # CACHE
  #######################

  redis:
    extends:
      file: docker-compose.rds.yml
      service: redis

  #######################
  # BROKER
  #######################

  zookeeper:
    extends:
      file: docker-compose.kfk.yml
      service: zookeeper

  kafka:
    extends:
      file: docker-compose.kfk.yml
      service: kafka
    depends_on:
      - zookeeper

  connect:
    extends:
      file: docker-compose.kfk.yml
      service: connect
    depends_on:
      - kafka

  kafka-ui:
    extends:
      file: docker-compose.kfk.yml
      service: kafka-ui
    depends_on:
      - kafka
      - connect

networks:
  localnet:
    driver: bridge
    name: wenex-network
